### PR TITLE
Add Github templates.

### PR DESCRIPTION
**Pull request by collin5**
Ref #6

### CODE REVIEW

**Comment by DavidNgugi** [comment]
@ProfNandaa What do you think about the PR Template? I think it's too minimal and doesn't tell me what has been changed

What about something like this?

### Which issue does this PR relate to?
- Please include the issue number of the task implemented in this PR 

### What are the changes implemented in the PR?
- What new functionality/feature has been added?
- Which packages have been installed
- Which files have been modified or refactored?

### How should the implementation be QA'd?
- What are the steps to follow to test the PR?
- What are edge cases to consider?
- What are the legacy browsers to test in?

### Anything else to note
- Maybe links to discussions related to the task
- Or even a reason why a secondary reviewer is needed for the task
N/A

### Screenshots and/or gifs (Optional)
- A visual view of the current changes

**Comment by Harrisonkamau** [comment]
@DavidNgugi That's a brilliant suggestion!! 
Some more below;

* For PR's that modify endpoints add a checklist for updating the docs, if it's an API.
* For Node projects, add a checklist for [versioning](https://docs.npmjs.com/cli/version). Update package:version with` npm version prepatch` (or premajor/preminor as appropriate)
* There are should be reviewers selected

**Comment by collin5** [comment]
Thanks for the feedback on this! I've tried to make changes to address the above comments. You could probably take another look. @DavidNgugi @Harrisonkamau

**Comment by collin5** [comment]
**Which issue does this PR relate to?**


**What are the changes implemented in the PR?**


**How should the implementation be QA'd or tested?**


**Todos**


**Anything else to note**


**Screenshots and/or gifs (Optional)**

**Comment by profnandaa** [comment]
Sweet 🎉

**Pull request merged**
